version: '3.5'

services:
  app:
    image: golang:latest
    container_name: golang_app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
        - .:/app/
    working_dir: /app/
    command: go run app.go
    restart: unless-stopped


